services:
  # Surcharge du service "web" pour le développement
  web:
    volumes:
      - ./logs/nginx:/var/log/nginx 

  # PhpMyAdmin avec réseau approprié
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db 
      PMA_PORT: 5432
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - frontend
      - database
      
  # Ajout de réseau pour la base de données
  db:
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  prometheus_data: {}

networks:
  frontend:
    external: true
  backend:
    external: true
  database:
    external: true