services:
  cron:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: cron
    env_file: ../.env
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
    depends_on:
      php-fpm-app:
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
    networks:
      - backend
      - database