services:
  php-fpm-app:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: php-fpm
    user: ${ORO_USER_RUNTIME:-www-data}
    env_file: ../.env
    healthcheck:
      test: "php-fpm-healthcheck"
      interval: 5s
      timeout: 30s
      start_period: 120s
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_started
      init:
        condition: service_completed_successfully
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - run_php_fpm:/run/php-fpm
    networks:
      - backend
      - database