services:
  restore: &restore
    image: ${ORO_IMAGE_INIT}${ORO_LANGUAGE_SUFFIX-}:$ORO_IMAGE_TAG
    command: restore
    user: $ORO_USER_RUNTIME
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_started
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data